//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ROZVRH {
    
    private string vYPSANE_TERMINYField;
    
    private ROZVRHKATEDRYKatedra[] kATEDRYField;
    
    private ROZVRHMISTNOSTIMistnost[] mISTNOSTIField;
    
    private ROZVRHPREDMETYPredmet[] pREDMETYField;
    
    private ROZVRHUCITELEUcitel[] uCITELEField;
    
    private ROZVRHLISTKYListek[] lISTKYField;
    
    private ROZVRHSTUDENTIStudent[] sTUDENTIField;
    
    private ROZVRHLISTKY_STUDENTUListek_studenta[] lISTKY_STUDENTUField;
    
    private ROZVRHJEDNORAZOVE_TERMINYJednorazova_akce[] jEDNORAZOVE_TERMINYField;
    
    private ROZVRHCASOVA_OKENKACasove_okenko[] cASOVA_OKENKAField;
    
    private ROZVRHZAPISY_PREDMETUZapis[] zAPISY_PREDMETUField;
    
    private ROZVRHZKOUSEJICIZkousejici_predmet[] zKOUSEJICIField;
    
    private ROZVRHZAPISY_JAZapis_jednorazovy_termin[] zAPISY_JAField;
    
    private ROZVRHZAPISY_NA_ZKOUSKYZapis_na_zkousku[] zAPISY_NA_ZKOUSKYField;
    
    private string semestrField;
    
    private string nazev_semestruField;
    
    private string aktsemField;
    
    private string aktsem2Field;
    
    private string zacatek_semField;
    
    private string konec_semField;
    
    private string stav_zapisuField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VYPSANE_TERMINY {
        get {
            return this.vYPSANE_TERMINYField;
        }
        set {
            this.vYPSANE_TERMINYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("katedra", typeof(ROZVRHKATEDRYKatedra), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHKATEDRYKatedra[] KATEDRY {
        get {
            return this.kATEDRYField;
        }
        set {
            this.kATEDRYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("mistnost", typeof(ROZVRHMISTNOSTIMistnost), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHMISTNOSTIMistnost[] MISTNOSTI {
        get {
            return this.mISTNOSTIField;
        }
        set {
            this.mISTNOSTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("predmet", typeof(ROZVRHPREDMETYPredmet), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHPREDMETYPredmet[] PREDMETY {
        get {
            return this.pREDMETYField;
        }
        set {
            this.pREDMETYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ucitel", typeof(ROZVRHUCITELEUcitel), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHUCITELEUcitel[] UCITELE {
        get {
            return this.uCITELEField;
        }
        set {
            this.uCITELEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("listek", typeof(ROZVRHLISTKYListek), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHLISTKYListek[] LISTKY {
        get {
            return this.lISTKYField;
        }
        set {
            this.lISTKYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("student", typeof(ROZVRHSTUDENTIStudent), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHSTUDENTIStudent[] STUDENTI {
        get {
            return this.sTUDENTIField;
        }
        set {
            this.sTUDENTIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("listek_studenta", typeof(ROZVRHLISTKY_STUDENTUListek_studenta), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHLISTKY_STUDENTUListek_studenta[] LISTKY_STUDENTU {
        get {
            return this.lISTKY_STUDENTUField;
        }
        set {
            this.lISTKY_STUDENTUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("jednorazova_akce", typeof(ROZVRHJEDNORAZOVE_TERMINYJednorazova_akce), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHJEDNORAZOVE_TERMINYJednorazova_akce[] JEDNORAZOVE_TERMINY {
        get {
            return this.jEDNORAZOVE_TERMINYField;
        }
        set {
            this.jEDNORAZOVE_TERMINYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("casove_okenko", typeof(ROZVRHCASOVA_OKENKACasove_okenko), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHCASOVA_OKENKACasove_okenko[] CASOVA_OKENKA {
        get {
            return this.cASOVA_OKENKAField;
        }
        set {
            this.cASOVA_OKENKAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("zapis", typeof(ROZVRHZAPISY_PREDMETUZapis), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHZAPISY_PREDMETUZapis[] ZAPISY_PREDMETU {
        get {
            return this.zAPISY_PREDMETUField;
        }
        set {
            this.zAPISY_PREDMETUField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("zkousejici_predmet", typeof(ROZVRHZKOUSEJICIZkousejici_predmet), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHZKOUSEJICIZkousejici_predmet[] ZKOUSEJICI {
        get {
            return this.zKOUSEJICIField;
        }
        set {
            this.zKOUSEJICIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("zapis_jednorazovy_termin", typeof(ROZVRHZAPISY_JAZapis_jednorazovy_termin), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHZAPISY_JAZapis_jednorazovy_termin[] ZAPISY_JA {
        get {
            return this.zAPISY_JAField;
        }
        set {
            this.zAPISY_JAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("zapis_na_zkousku", typeof(ROZVRHZAPISY_NA_ZKOUSKYZapis_na_zkousku), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public ROZVRHZAPISY_NA_ZKOUSKYZapis_na_zkousku[] ZAPISY_NA_ZKOUSKY {
        get {
            return this.zAPISY_NA_ZKOUSKYField;
        }
        set {
            this.zAPISY_NA_ZKOUSKYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string semestr {
        get {
            return this.semestrField;
        }
        set {
            this.semestrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazev_semestru {
        get {
            return this.nazev_semestruField;
        }
        set {
            this.nazev_semestruField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aktsem {
        get {
            return this.aktsemField;
        }
        set {
            this.aktsemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string aktsem2 {
        get {
            return this.aktsem2Field;
        }
        set {
            this.aktsem2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zacatek_sem {
        get {
            return this.zacatek_semField;
        }
        set {
            this.zacatek_semField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string konec_sem {
        get {
            return this.konec_semField;
        }
        set {
            this.konec_semField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stav_zapisu {
        get {
            return this.stav_zapisuField;
        }
        set {
            this.stav_zapisuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHKATEDRYKatedra {
    
    private string idField;
    
    private string kodField;
    
    private string nadrizenaField;
    
    private string nazev_czField;
    
    private string nazev_enField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nadrizena {
        get {
            return this.nadrizenaField;
        }
        set {
            this.nadrizenaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazev_cz {
        get {
            return this.nazev_czField;
        }
        set {
            this.nazev_czField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazev_en {
        get {
            return this.nazev_enField;
        }
        set {
            this.nazev_enField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHMISTNOSTIMistnost {
    
    private string cisloField;
    
    private string idField;
    
    private string kat_idField;
    
    private string lokField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cislo {
        get {
            return this.cisloField;
        }
        set {
            this.cisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kat_id {
        get {
            return this.kat_idField;
        }
        set {
            this.kat_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lok {
        get {
            return this.lokField;
        }
        set {
            this.lokField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHPREDMETYPredmet {
    
    private string poznamkaField;
    
    private string pozadavkyField;
    
    private string garantiField;
    
    private string idField;
    
    private string kat_idField;
    
    private string kodField;
    
    private string nazevField;
    
    private string nazev_anField;
    
    private string prkapacitaField;
    
    private string pr_forma_studiaField;
    
    private string pr_katedra_idField;
    
    private string pr_kredityField;
    
    private string pr_obsazenoField;
    
    private string pr_program_idField;
    
    private string pr_zapnutoField;
    
    private string pr_zpuszakField;
    
    private string rozsahField;
    
    private string sem_idField;
    
    private string pr_kapcvicField;
    
    private string pr_c_blokField;
    
    private string pr_p_blokField;
    
    private string pr_l_blokField;
    
    private string pr_znamky_hlasField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string poznamka {
        get {
            return this.poznamkaField;
        }
        set {
            this.poznamkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pozadavky {
        get {
            return this.pozadavkyField;
        }
        set {
            this.pozadavkyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string garanti {
        get {
            return this.garantiField;
        }
        set {
            this.garantiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kat_id {
        get {
            return this.kat_idField;
        }
        set {
            this.kat_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazev_an {
        get {
            return this.nazev_anField;
        }
        set {
            this.nazev_anField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("pr.kapacita")]
    public string prkapacita {
        get {
            return this.prkapacitaField;
        }
        set {
            this.prkapacitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_forma_studia {
        get {
            return this.pr_forma_studiaField;
        }
        set {
            this.pr_forma_studiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_katedra_id {
        get {
            return this.pr_katedra_idField;
        }
        set {
            this.pr_katedra_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_kredity {
        get {
            return this.pr_kredityField;
        }
        set {
            this.pr_kredityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_obsazeno {
        get {
            return this.pr_obsazenoField;
        }
        set {
            this.pr_obsazenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_program_id {
        get {
            return this.pr_program_idField;
        }
        set {
            this.pr_program_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_zapnuto {
        get {
            return this.pr_zapnutoField;
        }
        set {
            this.pr_zapnutoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_zpuszak {
        get {
            return this.pr_zpuszakField;
        }
        set {
            this.pr_zpuszakField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rozsah {
        get {
            return this.rozsahField;
        }
        set {
            this.rozsahField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sem_id {
        get {
            return this.sem_idField;
        }
        set {
            this.sem_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_kapcvic {
        get {
            return this.pr_kapcvicField;
        }
        set {
            this.pr_kapcvicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_c_blok {
        get {
            return this.pr_c_blokField;
        }
        set {
            this.pr_c_blokField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_p_blok {
        get {
            return this.pr_p_blokField;
        }
        set {
            this.pr_p_blokField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_l_blok {
        get {
            return this.pr_l_blokField;
        }
        set {
            this.pr_l_blokField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pr_znamky_hlas {
        get {
            return this.pr_znamky_hlasField;
        }
        set {
            this.pr_znamky_hlasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHUCITELEUcitel {
    
    private string idField;
    
    private string jmenoField;
    
    private string kat_idField;
    
    private string loginField;
    
    private string osoba_eidField;
    
    private string osobni_cisloField;
    
    private string prijmeniField;
    
    private string titul_predField;
    
    private string titul_zaField;
    
    private string uc_emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jmeno {
        get {
            return this.jmenoField;
        }
        set {
            this.jmenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kat_id {
        get {
            return this.kat_idField;
        }
        set {
            this.kat_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string osoba_eid {
        get {
            return this.osoba_eidField;
        }
        set {
            this.osoba_eidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string osobni_cislo {
        get {
            return this.osobni_cisloField;
        }
        set {
            this.osobni_cisloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prijmeni {
        get {
            return this.prijmeniField;
        }
        set {
            this.prijmeniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titul_pred {
        get {
            return this.titul_predField;
        }
        set {
            this.titul_predField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titul_za {
        get {
            return this.titul_zaField;
        }
        set {
            this.titul_zaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uc_email {
        get {
            return this.uc_emailField;
        }
        set {
            this.uc_emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHLISTKYListek {
    
    private string den_cisField;
    
    private string hodinaField;
    
    private string idField;
    
    private string konecField;
    
    private string pocet_hodinField;
    
    private string typ_vyukyField;
    
    private string ucitel1_idField;
    
    private string zacatekField;
    
    private string textField;
    
    private string cnoField;
    
    private string katedra1_idField;
    
    private string katedra2_idField;
    
    private string mistnost_idField;
    
    private string pnoField;
    
    private string predmet_idField;
    
    private string ucitel2_idField;
    
    private string lnoField;
    
    private string sudy_lichyField;
    
    private string par_jmenoField;
    
    private string paralelka_kodField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string den_cis {
        get {
            return this.den_cisField;
        }
        set {
            this.den_cisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hodina {
        get {
            return this.hodinaField;
        }
        set {
            this.hodinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string konec {
        get {
            return this.konecField;
        }
        set {
            this.konecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pocet_hodin {
        get {
            return this.pocet_hodinField;
        }
        set {
            this.pocet_hodinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typ_vyuky {
        get {
            return this.typ_vyukyField;
        }
        set {
            this.typ_vyukyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ucitel1_id {
        get {
            return this.ucitel1_idField;
        }
        set {
            this.ucitel1_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zacatek {
        get {
            return this.zacatekField;
        }
        set {
            this.zacatekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cno {
        get {
            return this.cnoField;
        }
        set {
            this.cnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string katedra1_id {
        get {
            return this.katedra1_idField;
        }
        set {
            this.katedra1_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string katedra2_id {
        get {
            return this.katedra2_idField;
        }
        set {
            this.katedra2_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mistnost_id {
        get {
            return this.mistnost_idField;
        }
        set {
            this.mistnost_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pno {
        get {
            return this.pnoField;
        }
        set {
            this.pnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string predmet_id {
        get {
            return this.predmet_idField;
        }
        set {
            this.predmet_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ucitel2_id {
        get {
            return this.ucitel2_idField;
        }
        set {
            this.ucitel2_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lno {
        get {
            return this.lnoField;
        }
        set {
            this.lnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sudy_lichy {
        get {
            return this.sudy_lichyField;
        }
        set {
            this.sudy_lichyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string par_jmeno {
        get {
            return this.par_jmenoField;
        }
        set {
            this.par_jmenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string paralelka_kod {
        get {
            return this.paralelka_kodField;
        }
        set {
            this.paralelka_kodField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHSTUDENTIStudent {
    
    private string fakultaField;
    
    private string forma_studiaField;
    
    private string idField;
    
    private string jmenoField;
    
    private string loginField;
    
    private string oborField;
    
    private string osoba_eidField;
    
    private string osoba_idField;
    
    private string prijmeniField;
    
    private string rocnikField;
    
    private string stlan_idField;
    
    private string stud_emailField;
    
    private string stud_idField;
    
    private string stud_programField;
    
    private string titulField;
    
    private string skupinaField;
    
    private string titul_zaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fakulta {
        get {
            return this.fakultaField;
        }
        set {
            this.fakultaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string forma_studia {
        get {
            return this.forma_studiaField;
        }
        set {
            this.forma_studiaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jmeno {
        get {
            return this.jmenoField;
        }
        set {
            this.jmenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string obor {
        get {
            return this.oborField;
        }
        set {
            this.oborField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string osoba_eid {
        get {
            return this.osoba_eidField;
        }
        set {
            this.osoba_eidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string osoba_id {
        get {
            return this.osoba_idField;
        }
        set {
            this.osoba_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prijmeni {
        get {
            return this.prijmeniField;
        }
        set {
            this.prijmeniField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rocnik {
        get {
            return this.rocnikField;
        }
        set {
            this.rocnikField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stlan_id {
        get {
            return this.stlan_idField;
        }
        set {
            this.stlan_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stud_email {
        get {
            return this.stud_emailField;
        }
        set {
            this.stud_emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stud_id {
        get {
            return this.stud_idField;
        }
        set {
            this.stud_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stud_program {
        get {
            return this.stud_programField;
        }
        set {
            this.stud_programField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titul {
        get {
            return this.titulField;
        }
        set {
            this.titulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string skupina {
        get {
            return this.skupinaField;
        }
        set {
            this.skupinaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titul_za {
        get {
            return this.titul_zaField;
        }
        set {
            this.titul_zaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHLISTKY_STUDENTUListek_studenta {
    
    private string listek_idField;
    
    private string student_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string listek_id {
        get {
            return this.listek_idField;
        }
        set {
            this.listek_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string student_id {
        get {
            return this.student_idField;
        }
        set {
            this.student_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHJEDNORAZOVE_TERMINYJednorazova_akce {
    
    private string casField;
    
    private string datumField;
    
    private string fakulta_idField;
    
    private string idField;
    
    private string kapacitaField;
    
    private string nazevField;
    
    private string obsazenoField;
    
    private string uzaverkaField;
    
    private string vypsal_idField;
    
    private string katedra_idField;
    
    private string misto_idField;
    
    private string predmet_idField;
    
    private string sem_idField;
    
    private string poznamkaField;
    
    private string oboryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cas {
        get {
            return this.casField;
        }
        set {
            this.casField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fakulta_id {
        get {
            return this.fakulta_idField;
        }
        set {
            this.fakulta_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kapacita {
        get {
            return this.kapacitaField;
        }
        set {
            this.kapacitaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazev {
        get {
            return this.nazevField;
        }
        set {
            this.nazevField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string obsazeno {
        get {
            return this.obsazenoField;
        }
        set {
            this.obsazenoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uzaverka {
        get {
            return this.uzaverkaField;
        }
        set {
            this.uzaverkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vypsal_id {
        get {
            return this.vypsal_idField;
        }
        set {
            this.vypsal_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string katedra_id {
        get {
            return this.katedra_idField;
        }
        set {
            this.katedra_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string misto_id {
        get {
            return this.misto_idField;
        }
        set {
            this.misto_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string predmet_id {
        get {
            return this.predmet_idField;
        }
        set {
            this.predmet_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sem_id {
        get {
            return this.sem_idField;
        }
        set {
            this.sem_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string poznamka {
        get {
            return this.poznamkaField;
        }
        set {
            this.poznamkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string obory {
        get {
            return this.oboryField;
        }
        set {
            this.oboryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHCASOVA_OKENKACasove_okenko {
    
    private string denField;
    
    private string idField;
    
    private string konecField;
    
    private string poznamkaField;
    
    private string zacatekField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string den {
        get {
            return this.denField;
        }
        set {
            this.denField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string konec {
        get {
            return this.konecField;
        }
        set {
            this.konecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string poznamka {
        get {
            return this.poznamkaField;
        }
        set {
            this.poznamkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zacatek {
        get {
            return this.zacatekField;
        }
        set {
            this.zacatekField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHZAPISY_PREDMETUZapis {
    
    private string predmet_idField;
    
    private string sem_idField;
    
    private string student_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string predmet_id {
        get {
            return this.predmet_idField;
        }
        set {
            this.predmet_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sem_id {
        get {
            return this.sem_idField;
        }
        set {
            this.sem_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string student_id {
        get {
            return this.student_idField;
        }
        set {
            this.student_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHZKOUSEJICIZkousejici_predmet {
    
    private string osoba_idField;
    
    private string predmet_idField;
    
    private string sem_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string osoba_id {
        get {
            return this.osoba_idField;
        }
        set {
            this.osoba_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string predmet_id {
        get {
            return this.predmet_idField;
        }
        set {
            this.predmet_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sem_id {
        get {
            return this.sem_idField;
        }
        set {
            this.sem_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHZAPISY_JAZapis_jednorazovy_termin {
    
    private string idField;
    
    private string student_idField;
    
    private string termin_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string student_id {
        get {
            return this.student_idField;
        }
        set {
            this.student_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string termin_id {
        get {
            return this.termin_idField;
        }
        set {
            this.termin_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ROZVRHZAPISY_NA_ZKOUSKYZapis_na_zkousku {
    
    private string datumField;
    
    private string idField;
    
    private string klasifikujiciField;
    
    private string sem_idField;
    
    private string student_idField;
    
    private string znamkaField;
    
    private string znamka_kodField;
    
    private string poznamkaField;
    
    private string nezapsanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string klasifikujici {
        get {
            return this.klasifikujiciField;
        }
        set {
            this.klasifikujiciField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sem_id {
        get {
            return this.sem_idField;
        }
        set {
            this.sem_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string student_id {
        get {
            return this.student_idField;
        }
        set {
            this.student_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string znamka {
        get {
            return this.znamkaField;
        }
        set {
            this.znamkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string znamka_kod {
        get {
            return this.znamka_kodField;
        }
        set {
            this.znamka_kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string poznamka {
        get {
            return this.poznamkaField;
        }
        set {
            this.poznamkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nezapsan {
        get {
            return this.nezapsanField;
        }
        set {
            this.nezapsanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private ROZVRH[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ROZVRH")]
    public ROZVRH[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
